name: lung_cancer_env
channels:
    - conda-forge
    - pytorch
    - defaults
dependencies:
    - python=3.10
    - pip
    - pytorch
    - torchvision
    - pip:
        - fastapi
        - uvicorn[standard]
        - pillow
        - python-multipart
        - tqdm
        - pytest
        - torchinfo
